name: Compare Versions
on:
  push:
    branches:
      - "*"

jobs:
  compare-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Test package.json version
        run: |
          # check main branch version
          git fetch origin main:main
          MAIN_VERSION=$(git show main:package.json | jq -r '.version')
          echo "Main Branch Package Version: $MAIN_VERSION"

          # check current branch verions
          CURRENT_VERSION=$(jq -r '.version' package.json)
          echo "Current Branch Package Version: $CURRENT_VERSION"

          # compare versions
          if [[ "$MAIN_VERSION" == "$CURRENT_VERSION" ]]; then
            echo "Error: Versions are the same."
            exit 1
          else
            echo "OK: Versions are different."
          fi
